/* BP4 mobile — bilingual content (es-419 · en) + contact constants.
   Lifted from the production site's strings layer, organized for the mobile build.
   Exposed on window.BP4M_DATA. */
window.BP4M_DATA = {
  contact: {
    whatsapp: "https://wa.me/5491164812711?text=Hola,%20quisiera%20saber%20m%C3%A1s%20sobre%20ustedes",
    email: "hello@bp-4.com",
    linkedin: "https://www.linkedin.com/company/bp4/",
    maps: "https://maps.app.goo.gl/Tkwnt6vTdSgQCxPr6",
    phone: "+54 9 11 6481-2711",
    address: "Chile 537, Buenos Aires, Argentina",
  },

  es: {
    code: "es-419",
    cta: "Hablemos",
    candidate: "¿Buscás trabajo?",
    nav: [
      { id: "modelo", label: "El modelo" },
      { id: "people-care", label: "People Care" },
      { id: "reporting", label: "Reporting" },
      { id: "recruiting", label: "Recruiting" },
      { id: "ia", label: "IA" },
      { id: "clientes", label: "Clientes" },
      { id: "contacto", label: "Contacto" },
    ],
    hero: {
      eyebrow: "Gestión integral de talento · +13 años",
      kicker: "El mejor staffing nace del match correcto.",
      title1: "Alineamos talento, cultura y objetivos para construir equipos que",
      titleEm: "permanecen.",
      body: "Combinamos recruiting especializado, gestión continua de personas, métricas y capacitación en un solo modelo. Así sostenemos equipos de alto desempeño a lo largo del tiempo.",
      primary: "Hablemos de tu equipo",
      secondary: "Conocé el modelo",
      snapshot: {
        title: "Salud de la cuenta",
        account: "Cuenta · Banca",
        statusLabel: "Operación estable",
        metrics: [
          { label: "Dotación activa", value: "24", tone: "ink" },
          { label: "Renovaciones al día", value: "100%", tone: "teal" },
          { label: "Riesgos detectados", value: "2", tone: "orange" },
        ],
        pillarsLabel: "Pilares activos",
        pillars: ["Recruiting", "People Care", "Reporting", "Capacitación"],
      },
    },
    stats: [
      ["+13", "años gestionando talento tech"],
      ["+100", "colaboradores en proyectos críticos"],
      ["+10", "empresas líderes confían en BP4"],
    ],
    clients: {
      eyebrow: "Clientes",
      title: "Gestionamos equipos para empresas líderes",
      body: "Banca, telco, consumo masivo, salud, automotriz y tecnología.",
      stat: "+100 colaboradores gestionados en proyectos críticos de negocio.",
      names: ["Banco", "Telco", "Retail", "Salud", "Automotriz", "Tech"],
    },
    challenge: {
      eyebrow: "El desafío",
      title1: "Incorporar talento es importante.",
      titleEm: "Sostenerlo es lo que genera valor.",
      body: "La mayoría concentra el esfuerzo en contratar. Pero los mayores desafíos aparecen después de la incorporación — y ahí se define el resultado.",
      needsTitle: "Lo que cada parte necesita",
      needs: [
        { who: "Los equipos", what: "mantenerse productivos, motivados y alineados al negocio." },
        { who: "Los líderes", what: "visibilidad sobre lo que pasa en la operación." },
        { who: "Recursos Humanos", what: "información clara para decidir." },
        { who: "Tecnología", what: "estabilidad operativa sostenida." },
        { who: "Los colaboradores", what: "acompañamiento, desarrollo y claridad sobre su crecimiento." },
      ],
      risksTitle: "Cuando algo de eso falla",
      risksLead: "Aparecen los costos que nadie planifica:",
      risks: ["Rotación", "Pérdida de productividad", "Demoras en proyectos", "Desgaste de los equipos", "Aumento de costos"],
      close: "BP4 fue construido para gestionar esa complejidad.",
    },
    model: {
      eyebrow: "Nuestro modelo",
      title1: "Cuatro capacidades integradas,",
      titleEm: "un solo equipo.",
      body: "Evolucionamos del staffing tradicional a un modelo integral de gestión de talento.",
      pillars: [
        { icon: "search", tag: "01", title: "Recruiting", body: "Identificación, evaluación e incorporación de talento tecnológico especializado." },
        { icon: "heart-handshake", tag: "02", title: "People Care", body: "Gestión continua de cada colaborador durante toda su permanencia en el proyecto." },
        { icon: "bar-chart-3", tag: "03", title: "Reporting", body: "Métricas e información accionable para la toma de decisiones." },
        { icon: "graduation-cap", tag: "04", title: "Desarrollo y Capacitaciones", body: "Evolución de las capacidades técnicas y profesionales de los equipos." },
      ],
    },
    recruiting: {
      eyebrow: "Recruiting",
      title: "Recruiting especializado en tecnología",
      body: "Trabajamos exclusivamente sobre perfiles tecnológicos. El conocimiento técnico acumulado nos permite evaluar con una mirada alineada a la realidad de los proyectos.",
      profilesTitle: "Perfiles que buscamos",
      profiles: ["Backend", "Frontend", "Fullstack", "Consultores SAP", "Consultores COBOL", "UX/UI", "QA Manual & Automation", "Analistas Funcionales", "Scrum Masters", "Project Managers", "Líderes Técnicos", "Arquitectos", "Especialistas Cloud", "Perfiles de IA"],
      punch: "Nuestro objetivo no es presentar candidatos. Es generar el mejor match entre el profesional, el proyecto y la organización.",
    },
    peopleCare: {
      eyebrow: "People Care",
      title: "El corazón del modelo BP4",
      body: "A diferencia del staff augmentation tradicional, mantenemos una gestión activa y permanente durante toda la asignación. Detectamos riesgos antes de que impacten en la operación.",
      dimsLead: "Combinamos dos dimensiones complementarias para comprender el contexto completo de cada colaborador.",
      dims: [
        { tag: "Dimensión operativa", icon: "clipboard-list", items: ["Gestión contractual", "Renovaciones y ajustes", "Licencias y vacaciones", "Horas y horas extra", "Consumo de presupuesto", "Seguimiento administrativo", "Control de desvíos operativos"] },
        { tag: "Dimensión humana", icon: "heart", items: ["Clima laboral", "Motivación y satisfacción", "Integración al equipo", "Relación con líderes", "Expectativas profesionales", "Desarrollo de carrera", "Sentido de pertenencia"] },
      ],
      focalTitle: "El rol del focal point",
      focalBody: "Trabajamos junto a un referente del cliente —de RR.HH. o Talent Management— para centralizar la comunicación y asegurar una visión integral de la dotación. No reemplaza la relación con los managers: la ordena y la potencia.",
    },
    reporting: {
      eyebrow: "Reporting",
      title: "Gestión basada en datos, no en intuición",
      body: "La estabilidad de los equipos se gestiona con información. Transformamos datos dispersos en conocimiento útil para decidir.",
      measureTitle: "Qué medimos",
      measures: ["Rotación", "Riesgos detectados", "Intervenciones", "Tiempo de cobertura", "Renovaciones", "Evolución de dotación", "Desvíos operativos", "Match colaborador–proyecto", "Necesidades de capacitación", "Salud de la cuenta"],
      reportTitle: "Reporte ejecutivo + dashboards",
      reportBody: "Consolidamos lo más relevante en un reporte ejecutivo y lo complementamos con dashboards interactivos en tiempo real. No solo describimos lo que ocurrió — anticipamos lo que puede ocurrir.",
      reportLabel: "Reporte ejecutivo",
      dashLabel: "Dashboard en vivo",
      detectTitle: "Qué nos permite anticipar",
      detect: ["Desajustes entre seniority y responsabilidades", "Necesidades de capacitación", "Riesgos de rotación", "Problemas de adaptación al proyecto", "Sobrecarga de trabajo y horas extra", "Expectativas desalineadas", "Oportunidades de desarrollo profesional"],
    },
    ai: {
      eyebrow: "Innovación",
      title: "Inteligencia Artificial aplicada a tus equipos",
      body: "Desarrollamos una línea enfocada en adopción, capacitación y medición de impacto. No solo enseñamos herramientas — ayudamos a capturar valor real.",
      utnTag: "Partnership",
      utnTitle: "Programas junto a la UTN",
      utnBody: "Junto a la Universidad Tecnológica Nacional transformamos la adopción espontánea de IA en una ventaja competitiva medible.",
      items: ["Diagnóstico inicial", "Formación práctica", "Casos de uso reales", "Frameworks de adopción", "Playbooks", "Métricas de impacto", "Roadmaps de implementación"],
    },
    diff: {
      eyebrow: "Qué nos diferencia",
      title: "Combinamos lo que otros tienen separado.",
      verbs: ["Reclutamos.", "Gestionamos.", "Medimos.", "Desarrollamos.", "Capacitamos.", "Acompañamos."],
      punch: "Nuestro diferencial no es solo encontrar talento. Es ayudar a que ese talento permanezca, evolucione y genere impacto sostenido.",
    },
    vision: {
      eyebrow: "Nuestra visión",
      title: "El socio estratégico para construir y sostener equipos tech de alto desempeño.",
      body: "Combinamos experiencia técnica, gestión basada en métricas y cercanía con las personas. Los mejores resultados llegan cuando tecnología, procesos y personas van en la misma dirección.",
    },
    ctaBand: {
      eyebrow: "Empecemos",
      title: "Construyamos tu próxima operación tecnológica",
      body: "Contanos qué equipo necesitás gestionar. Te respondemos en 24hs.",
      button: "Hablemos de tu equipo",
      whatsapp: "Escribinos por WhatsApp",
    },
    contact: {
      eyebrow: "Hablemos",
      title: "Hablemos de tu equipo",
      body: "Contanos qué buscás y nos ponemos en campaña. Te respondemos en 24hs.",
      fields: [
        { key: "name", label: "Tu nombre", ph: "¿Cómo te llamás?" },
        { key: "email", label: "Email de trabajo", ph: "vos@empresa.com" },
        { key: "need", label: "¿En qué podemos ayudarte?", ph: "Ej: gestionar un squad de 8 devs + QA", area: true },
      ],
      submit: "Enviar consulta",
      hint: "Te respondemos en 24hs. Sin compromiso.",
      directTitle: "O escribinos directo",
    },
    footer: {
      tagline: "Gestión integral de talento tecnológico.",
      somos: ["Somos IT.", "Gestionamos talento", "de punta a punta."],
      legal: "© 2026 BP4. Hecho con buena onda.",
    },
    ui: { menu: "Menú", expand: "Ver todo", collapse: "Ver menos", office: "Oficina" },
  },

  en: {
    code: "en",
    cta: "Let's talk",
    candidate: "Looking for a job?",
    nav: [
      { id: "modelo", label: "The model" },
      { id: "people-care", label: "People Care" },
      { id: "reporting", label: "Reporting" },
      { id: "recruiting", label: "Recruiting" },
      { id: "ia", label: "AI" },
      { id: "clientes", label: "Clients" },
      { id: "contacto", label: "Contact" },
    ],
    hero: {
      eyebrow: "End-to-end talent management · 13+ years",
      kicker: "Great staffing starts with the right match.",
      title1: "We align talent, culture and goals to build teams that",
      titleEm: "stay.",
      body: "We combine specialized recruiting, continuous people management, metrics and training in a single model. That's how we sustain high-performance teams over time.",
      primary: "Let's talk about your team",
      secondary: "See the model",
      snapshot: {
        title: "Account health",
        account: "Account · Banking",
        statusLabel: "Stable operation",
        metrics: [
          { label: "Active headcount", value: "24", tone: "ink" },
          { label: "Renewals on track", value: "100%", tone: "teal" },
          { label: "Risks flagged", value: "2", tone: "orange" },
        ],
        pillarsLabel: "Active pillars",
        pillars: ["Recruiting", "People Care", "Reporting", "Training"],
      },
    },
    stats: [
      ["13+", "years managing tech talent"],
      ["100+", "people on critical projects"],
      ["10+", "leading companies trust BP4"],
    ],
    clients: {
      eyebrow: "Clients",
      title: "We manage teams for leading companies",
      body: "Banking, telco, consumer goods, healthcare, automotive and tech.",
      stat: "100+ people managed on business-critical projects.",
      names: ["Bank", "Telco", "Retail", "Health", "Auto", "Tech"],
    },
    challenge: {
      eyebrow: "The challenge",
      title1: "Hiring talent matters.",
      titleEm: "Sustaining it is what creates value.",
      body: "Most companies focus on hiring. But the biggest challenges appear after onboarding — and that's where the outcome is decided.",
      needsTitle: "What each side needs",
      needs: [
        { who: "Teams", what: "to stay productive, motivated and aligned with the business." },
        { who: "Leaders", what: "visibility into what's happening in the operation." },
        { who: "HR", what: "clear information to decide." },
        { who: "Technology", what: "sustained operational stability." },
        { who: "People", what: "support, growth and clarity about their path." },
      ],
      risksTitle: "When any of that fails",
      risksLead: "The costs no one planned for show up:",
      risks: ["Turnover", "Lost productivity", "Project delays", "Team burnout", "Rising costs"],
      close: "BP4 was built to manage that complexity.",
    },
    model: {
      eyebrow: "Our model",
      title1: "Four integrated capabilities,",
      titleEm: "one team.",
      body: "We evolved from traditional staffing into an integrated talent-management model.",
      pillars: [
        { icon: "search", tag: "01", title: "Recruiting", body: "Sourcing, assessment and onboarding of specialized tech talent." },
        { icon: "heart-handshake", tag: "02", title: "People Care", body: "Continuous management of every person throughout the assignment." },
        { icon: "bar-chart-3", tag: "03", title: "Reporting", body: "Metrics and actionable information for decision-making." },
        { icon: "graduation-cap", tag: "04", title: "Development & Training", body: "Growing the technical and professional capabilities of teams." },
      ],
    },
    recruiting: {
      eyebrow: "Recruiting",
      title: "Recruiting specialized in technology",
      body: "We work exclusively on tech profiles. The technical knowledge built over years lets us assess with a lens aligned to the reality of projects.",
      profilesTitle: "Profiles we source",
      profiles: ["Backend", "Frontend", "Fullstack", "SAP Consultants", "COBOL Consultants", "UX/UI", "QA Manual & Automation", "Functional Analysts", "Scrum Masters", "Project Managers", "Tech Leads", "Architects", "Cloud Specialists", "AI Profiles"],
      punch: "Our goal isn't to present candidates. It's to create the best match between the professional, the project and the organization.",
    },
    peopleCare: {
      eyebrow: "People Care",
      title: "The heart of the BP4 model",
      body: "Unlike traditional staff augmentation, we keep active, permanent management throughout the assignment. We spot risks before they hit the operation.",
      dimsLead: "We combine two complementary dimensions to understand each person's full context.",
      dims: [
        { tag: "Operational dimension", icon: "clipboard-list", items: ["Contract management", "Renewals & adjustments", "Leave & vacations", "Hours & overtime", "Budget consumption", "Administrative tracking", "Operational deviation control"] },
        { tag: "Human dimension", icon: "heart", items: ["Work climate", "Motivation & satisfaction", "Team integration", "Relationship with leaders", "Professional expectations", "Career development", "Sense of belonging"] },
      ],
      focalTitle: "The focal point role",
      focalBody: "We work alongside a client referent —from HR or Talent Management— to centralize communication and ensure an integral view of the headcount. It doesn't replace the relationship with managers: it organizes and amplifies it.",
    },
    reporting: {
      eyebrow: "Reporting",
      title: "Data-driven management, not intuition",
      body: "Team stability is managed with information. We turn scattered data into knowledge that's useful for deciding.",
      measureTitle: "What we measure",
      measures: ["Turnover", "Risks flagged", "Interventions", "Coverage time", "Renewals", "Headcount evolution", "Operational deviations", "Person–project match", "Training needs", "Account health"],
      reportTitle: "Executive report + dashboards",
      reportBody: "We consolidate the most relevant information into an executive report, complemented by interactive dashboards in real time. We don't only describe what happened — we anticipate what may happen.",
      reportLabel: "Executive report",
      dashLabel: "Live dashboard",
      detectTitle: "What it lets us anticipate",
      detect: ["Seniority vs. responsibility mismatches", "Training needs", "Turnover risks", "Project adaptation issues", "Workload and overtime", "Misaligned expectations", "Professional development opportunities"],
    },
    ai: {
      eyebrow: "Innovation",
      title: "Artificial Intelligence applied to your teams",
      body: "We built a practice focused on adoption, training and impact measurement. We don't only teach tools — we help teams capture real value.",
      utnTag: "Partnership",
      utnTitle: "Programs with UTN",
      utnBody: "Together with Universidad Tecnológica Nacional we turn spontaneous AI adoption into a measurable competitive advantage.",
      items: ["Initial diagnosis", "Hands-on training", "Real use cases", "Adoption frameworks", "Playbooks", "Impact metrics", "Implementation roadmaps"],
    },
    diff: {
      eyebrow: "What sets us apart",
      title: "We combine what others keep separate.",
      verbs: ["We recruit.", "We manage.", "We measure.", "We develop.", "We train.", "We support."],
      punch: "Our edge isn't only finding talent. It's helping that talent stay, evolve and create sustained impact.",
    },
    vision: {
      eyebrow: "Our vision",
      title: "The strategic partner to build and sustain high-performance tech teams.",
      body: "We combine technical experience, metrics-based management and closeness to people. The best results happen when technology, processes and people move in the same direction.",
    },
    ctaBand: {
      eyebrow: "Let's start",
      title: "Let's build your next technology operation",
      body: "Tell us which team you need to manage. We reply within 24h.",
      button: "Let's talk about your team",
      whatsapp: "Message us on WhatsApp",
    },
    contact: {
      eyebrow: "Let's talk",
      title: "Let's talk about your team",
      body: "Tell us what you're after and we'll get to work. We reply within 24h.",
      fields: [
        { key: "name", label: "Your name", ph: "What's your name?" },
        { key: "email", label: "Work email", ph: "you@company.com" },
        { key: "need", label: "How can we help?", ph: "e.g. manage a squad of 8 devs + QA", area: true },
      ],
      submit: "Send request",
      hint: "We reply within 24h. No strings attached.",
      directTitle: "Or reach us directly",
    },
    footer: {
      tagline: "End-to-end tech talent management.",
      somos: ["We're IT.", "We manage talent", "end to end."],
      legal: "© 2026 BP4. Made with good vibes.",
    },
    ui: { menu: "Menu", expand: "Show all", collapse: "Show less", office: "Office" },
  },
};
